service: sls-exemplar

provider:
  name: aws
  runtime: nodejs12.x

functions:
  exemplar:
    handler: src/exemplar.endpoint
    events:
      - http:
          path: exemplar
          method: post
          cors: true
  buyer-choice:
    handler: src/buyer-choice/handler.endpoint
    events:
      - http:
          path: buyer-choice
          method: post
          cors: true